name: serverless-terraform

on:
  pull_request:
    paths:
      - "projects/02-serverless-gha/**"
      - "modules/**"
      - ".github/workflows/serverless-terraform.yml"
  push:
    branches: ["main"]
    paths:
      - "projects/02-serverless-gha/**"
      - "modules/**"
      - ".github/workflows/serverless-terraform.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/02-serverless-gha
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GHA_TERRAFORM_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Terraform init
        run: terraform init -reconfigure -backend-config=../../shared/backend/dev.hcl -backend-config="key=02-serverless-gha/dev/terraform.tfstate"

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -no-color
        continue-on-error: true

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: projects/02-serverless-gha
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GHA_TERRAFORM_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Terraform init
        run: terraform init -reconfigure -backend-config=../../shared/backend/dev.hcl -backend-config="key=02-serverless-gha/dev/terraform.tfstate"

      - name: Terraform apply
        run: terraform apply -auto-approve